services:
  mongo1:
    image: mongo:8.0.0
    hostname: mongo1
    container_name: mongo1
    ports:
      - 27017:27017
    entrypoint:
      ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo1"]

  mongo2:
    image: mongo:8.0.0
    hostname: mongo2
    container_name: mongo2
    ports:
      - 27018:27017
    entrypoint:
      ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo2"]

  mongo3:
    image: mongo:8.0.0
    hostname: mongo3
    container_name: mongo3
    ports:
      - 27019:27017
    entrypoint:
      ["mongod", "--replSet", "myReplicaSet", "--bind_ip", "localhost,mongo3"]

  mongosetup:
    image: mongo:latest
    container_name: mongosetup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./mongo_setup.sh:/scripts/mongo_setup.sh
    restart: "no"
    entrypoint: ["bash", "/scripts/mongo_setup.sh"]
