services:
  metastore-standalone:
    image: apache/hive:4.0.1
    container_name: metastore-standalone
    networks:
      broker:
        ipv4_address: 172.18.0.30
    ports:
      - 9083:9083
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      # - HIVE_CUSTOM_CONF_DIR=/hive_custom_conf
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password
    volumes:
      - ./driver/postgresql-42.7.4.jar:/opt/hive/lib/postgresql-42.7.4.jar
      - ./warehouse-mst:/opt/hive/data/warehouse # Persist Hive warehouse data
      # - ./conf:/hive_custom_conf  # Mount local config directory to container
    # restart: always  # Optional: will restart the container if it stops
    depends_on:
      - postgres # Ensure metastore starts after PostgreSQL is available
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9083"]
      interval: 10s
      retries: 5

  hiveserver2-standalone:
    image: apache/hive:4.0.1
    container_name: hiveserver2-standalone
    networks:
      broker:
        ipv4_address: 172.18.0.31
    ports:
      - 10000:10000
      - 10002:10002
    environment:
      - SERVICE_NAME=hiveserver2
      - SERVICE_OPTS=-Dhive.metastore.uris=thrift://metastore-standalone:9083
      - IS_RESUME=true
    volumes:
      - ./warehouse-hs2:/opt/hive/data/warehouse # Persist Hive warehouse data
    # restart: always  # Optional: will restart the container if it stops
    depends_on:
      - metastore-standalone # Ensure this starts after the metastore is available

  postgres:
    image: postgres:16.4
    container_name: postgres
    networks:
      broker:
        ipv4_address: 172.18.0.40
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=metastore_db
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    # restart: always # Optional: will restart the container if it stops
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "hive",
          "-d",
          "metastore_db",
          "-h",
          "localhost",
        ]
      interval: 10s
      retries: 3

networks:
  broker:
    external: true
    name: broker-net
