services:
  mysql:
    image: mysql:lts
    container_name: mysql
    networks:
      broker:
        ipv4_address: 172.18.0.41
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=telecomdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./scripts:/scripts
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

networks:
  broker:
    external: true
    name: broker-net
