services:
  minio1:
    image: quay.io/minio/minio:latest
    container_name: minio1
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio1/data:/data
    environment:
      MINIO_ROOT_USER: ROOTUSER
      MINIO_ROOT_PASSWORD: CHANGEME123
    command: server /data --console-address ":9001"
